# Generated by Django 3.1.4 on 2020-12-17 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reflection', models.TextField()),
                ('owner', models.ForeignKey(default='owner reflections', on_delete=django.db.models.deletion.CASCADE, related_name='owned_reflections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.PositiveSmallIntegerField()),
                ('sleep', models.PositiveSmallIntegerField()),
                ('exercise', models.PositiveSmallIntegerField()),
                ('calories', models.PositiveSmallIntegerField()),
                ('learning', models.PositiveSmallIntegerField()),
                ('spending', models.PositiveSmallIntegerField()),
                ('earning', models.PositiveSmallIntegerField()),
                ('travel', models.PositiveSmallIntegerField()),
                ('date', models.DateField(unique=True)),
                ('owner', models.ForeignKey(default='owner habits', on_delete=django.db.models.deletion.CASCADE, related_name='owned_habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.PositiveSmallIntegerField()),
                ('sleep', models.PositiveSmallIntegerField()),
                ('exercise', models.PositiveSmallIntegerField()),
                ('calories', models.PositiveSmallIntegerField()),
                ('learning', models.PositiveSmallIntegerField()),
                ('spending', models.PositiveSmallIntegerField()),
                ('earning', models.PositiveSmallIntegerField()),
                ('travel', models.PositiveSmallIntegerField()),
                ('date', models.DateField(default='2020-12-17', unique=True)),
                ('owner', models.ForeignKey(default='owner goals', on_delete=django.db.models.deletion.CASCADE, related_name='owned_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
