# Generated by Django 3.1.4 on 2020-12-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.PositiveSmallIntegerField()),
                ('sleep', models.PositiveSmallIntegerField()),
                ('exercise', models.PositiveSmallIntegerField()),
                ('calories', models.PositiveSmallIntegerField()),
                ('learning', models.PositiveSmallIntegerField()),
                ('spending', models.PositiveSmallIntegerField()),
                ('earning', models.PositiveSmallIntegerField()),
                ('travel', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.PositiveSmallIntegerField()),
                ('sleep', models.PositiveSmallIntegerField()),
                ('exercise', models.PositiveSmallIntegerField()),
                ('calories', models.PositiveSmallIntegerField()),
                ('learning', models.PositiveSmallIntegerField()),
                ('spending', models.PositiveSmallIntegerField()),
                ('earning', models.PositiveSmallIntegerField()),
                ('travel', models.PositiveSmallIntegerField()),
                ('date', models.DateField(auto_now_add=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('reflection', models.TextField()),
            ],
        ),
    ]
